name: code-analysis

on:
  pull_request:
    branches:
      - main

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install capm
        run: pipx install capm

      - name: Run capm
        run: capm run
